server:
  port: 8080
  name: "central orchestrator"
  metricsport: 9200 
git:
  owner: edge-orchestration-platform
  repo: deployments
  branch: main
  private: true
  token_env: GITHUB_TOKEN
appregistry:
  repo: https://github.com/edge-orchestration-platform/app-registry
  branch: main
mode: push