name: Docker Compose CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and start all services
        run: |
          docker compose -f docker-compose.yml up -d --build
          docker compose ps

      - name: Wait for services to be ready
        run: |
          echo "Waiting 15s for services..."
          sleep 15

      - name: Print service logs
        run: |
          docker logs intelligent-edge-orchestrator-co-1 || true
          docker logs intelligent-edge-orchestrator-lo_1-1 || true
          docker logs intelligent-edge-orchestrator-lo_2-1 || true

      - name: Health check
        run: |
          curl -s http://localhost:9001/health || echo "CO not ready"
          curl -s http://localhost:9010/health || echo "LO_1 not ready"
          curl -s http://localhost:9011/health || echo "LO_2 not ready"


      # - name: Run smoke test
      #   run: |
      #     # docker exec co curl -s http://localhost:9001/health || echo "CO not ready"
      #     # docker exec lo_1 curl -s http://localhost:9010/health || echo "LO_1 not ready"
      #     # docker exec lo_2 curl -s http://localhost:9011/health || echo "LO_2 not ready"
      #     docker exec intelligent-edge-orchestrator-co-1 curl -s http://localhost:9001/health || echo "CO not ready"
      #     docker exec intelligent-edge-orchestrator-lo_1-1 curl -s http://localhost:9010/health || echo "LO_1 not ready"
      #     docker exec intelligent-edge-orchestrator-lo_2-1 curl -s http://localhost:9011/health || echo "LO_2 not ready"
      - name: Stop all containers
        run: docker compose -f docker-compose.yml down -v
